import type { EmailBlock } from '@/lib/supabase/types'

export interface StarterTemplate {
  id: string
  name: string
  description: string
  category: string
  blocks: EmailBlock[]
  thumbnailBg: string
}

const STARTER_NEWSLETTER: EmailBlock[] = [
  {
    id: 'starter-newsletter-1',
    type: 'heading',
    headingTag: 'h1',
    headingText: 'Your Newsletter Title',
    fontSize: 32,
    color: '#1B1B1B',
    alignment: 'center',
    paddingTop: 16,
    paddingBottom: 8,
    paddingLeft: 0,
    paddingRight: 0,
  },
  {
    id: 'starter-newsletter-2',
    type: 'text',
    textContent: 'Welcome to our newsletter! Here is what we have for you this week.',
    fontSize: 15,
    color: '#4B4B4B',
    alignment: 'left',
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 0,
    paddingRight: 0,
  },
  {
    id: 'starter-newsletter-3',
    type: 'divider',
    dividerColor: '#E5E7EB',
    dividerThickness: 1,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 0,
    paddingRight: 0,
    alignment: 'left',
  },
  {
    id: 'starter-newsletter-4',
    type: 'button',
    buttonLabel: 'Read More',
    buttonUrl: '#',
    buttonBgColor: '#16DAC1',
    buttonTextColor: '#FFFFFF',
    buttonRadius: 100,
    alignment: 'center',
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 0,
    paddingRight: 0,
  },
  {
    id: 'starter-newsletter-5',
    type: 'social',
    alignment: 'center',
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 0,
    paddingRight: 0,
    socialIconSize: 36,
    socialIconBgColor: '',
    socialIconColor: '#FFFFFF',
    socialIconRadius: 50,
    socialLinks: [
      { platform: 'facebook', url: 'https://facebook.com', enabled: true },
      { platform: 'instagram', url: 'https://instagram.com', enabled: true },
      { platform: 'linkedin', url: 'https://linkedin.com', enabled: true },
      { platform: 'youtube', url: 'https://youtube.com', enabled: false },
      { platform: 'twitter', url: 'https://twitter.com', enabled: false },
      { platform: 'tiktok', url: 'https://tiktok.com', enabled: false },
    ],
  },
]

const STARTER_PROMO: EmailBlock[] = [
  {
    id: 'starter-promo-1',
    type: 'image',
    imageUrl: '',
    imageAlt: 'Promotional banner',
    imageLink: '',
    imageWidth: 100,
    alignment: 'center',
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
  },
  {
    id: 'starter-promo-2',
    type: 'heading',
    headingTag: 'h1',
    headingText: 'Special Offer Just for You',
    fontSize: 28,
    color: '#1B1B1B',
    alignment: 'center',
    paddingTop: 24,
    paddingBottom: 8,
    paddingLeft: 0,
    paddingRight: 0,
  },
  {
    id: 'starter-promo-3',
    type: 'text',
    textContent: 'Don\'t miss out on our exclusive deal. Limited time only!',
    fontSize: 15,
    color: '#4B4B4B',
    alignment: 'center',
    paddingTop: 8,
    paddingBottom: 16,
    paddingLeft: 0,
    paddingRight: 0,
  },
  {
    id: 'starter-promo-4',
    type: 'button',
    buttonLabel: 'Claim Your Offer',
    buttonUrl: '#',
    buttonBgColor: '#16DAC1',
    buttonTextColor: '#FFFFFF',
    buttonRadius: 100,
    alignment: 'center',
    paddingTop: 16,
    paddingBottom: 24,
    paddingLeft: 0,
    paddingRight: 0,
  },
]

const STARTER_ONBOARDING: EmailBlock[] = [
  {
    id: 'starter-onboarding-1',
    type: 'heading',
    headingTag: 'h1',
    headingText: 'Welcome, {{first_name}}!',
    fontSize: 28,
    color: '#1B1B1B',
    alignment: 'center',
    paddingTop: 24,
    paddingBottom: 8,
    paddingLeft: 0,
    paddingRight: 0,
  },
  {
    id: 'starter-onboarding-2',
    type: 'text',
    textContent: 'We\'re thrilled to have you on board. Here\'s how to get started.',
    fontSize: 15,
    color: '#4B4B4B',
    alignment: 'left',
    paddingTop: 8,
    paddingBottom: 16,
    paddingLeft: 0,
    paddingRight: 0,
  },
  {
    id: 'starter-onboarding-3',
    type: 'button',
    buttonLabel: 'Get Started',
    buttonUrl: '#',
    buttonBgColor: '#16DAC1',
    buttonTextColor: '#FFFFFF',
    buttonRadius: 100,
    alignment: 'center',
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 0,
    paddingRight: 0,
  },
  {
    id: 'starter-onboarding-4',
    type: 'divider',
    dividerColor: '#E5E7EB',
    dividerThickness: 1,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 0,
    paddingRight: 0,
    alignment: 'left',
  },
  {
    id: 'starter-onboarding-5',
    type: 'text',
    textContent: 'Questions? Reply to this email or visit our help center. | <a href="{{unsubscribe_url}}">Unsubscribe</a>',
    fontSize: 12,
    color: '#9CA3AF',
    alignment: 'center',
    paddingTop: 8,
    paddingBottom: 16,
    paddingLeft: 0,
    paddingRight: 0,
  },
]

const STARTER_REACTIVATION: EmailBlock[] = [
  {
    id: 'starter-reactivation-1',
    type: 'heading',
    headingTag: 'h2',
    headingText: 'We Miss You, {{first_name}}',
    fontSize: 26,
    color: '#1B1B1B',
    alignment: 'center',
    paddingTop: 24,
    paddingBottom: 8,
    paddingLeft: 0,
    paddingRight: 0,
  },
  {
    id: 'starter-reactivation-2',
    type: 'text',
    textContent: 'It\'s been a while since we last connected. We\'ve been working on some exciting things and we\'d love to share them with you.',
    fontSize: 15,
    color: '#4B4B4B',
    alignment: 'center',
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 0,
    paddingRight: 0,
  },
  {
    id: 'starter-reactivation-3',
    type: 'text',
    textContent: 'Here\'s what\'s new for you:',
    fontSize: 15,
    color: '#4B4B4B',
    alignment: 'left',
    paddingTop: 8,
    paddingBottom: 16,
    paddingLeft: 0,
    paddingRight: 0,
  },
  {
    id: 'starter-reactivation-4',
    type: 'button',
    buttonLabel: 'Come Back & Explore',
    buttonUrl: '#',
    buttonBgColor: '#16DAC1',
    buttonTextColor: '#FFFFFF',
    buttonRadius: 100,
    alignment: 'center',
    paddingTop: 16,
    paddingBottom: 24,
    paddingLeft: 0,
    paddingRight: 0,
  },
]

const STARTER_TRANSACTIONAL: EmailBlock[] = [
  {
    id: 'starter-transactional-1',
    type: 'heading',
    headingTag: 'h2',
    headingText: 'Order Confirmation',
    fontSize: 24,
    color: '#1B1B1B',
    alignment: 'left',
    paddingTop: 16,
    paddingBottom: 8,
    paddingLeft: 0,
    paddingRight: 0,
  },
  {
    id: 'starter-transactional-2',
    type: 'text',
    textContent: 'Hi {{first_name}}, your order has been confirmed. Here are the details:',
    fontSize: 15,
    color: '#4B4B4B',
    alignment: 'left',
    paddingTop: 8,
    paddingBottom: 16,
    paddingLeft: 0,
    paddingRight: 0,
  },
  {
    id: 'starter-transactional-3',
    type: 'divider',
    dividerColor: '#E5E7EB',
    dividerThickness: 1,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 0,
    paddingRight: 0,
    alignment: 'left',
  },
  {
    id: 'starter-transactional-4',
    type: 'text',
    textContent: 'If you have any questions, please contact our support team. We\'re here to help.',
    fontSize: 13,
    color: '#6B7280',
    alignment: 'left',
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 0,
    paddingRight: 0,
  },
]

export const STARTER_TEMPLATES: StarterTemplate[] = [
  {
    id: 'tpl-newsletter',
    name: 'Newsletter',
    description: 'A clean newsletter layout with heading, text, divider, button and social links.',
    category: 'newsletter',
    blocks: STARTER_NEWSLETTER,
    thumbnailBg: 'bg-sky-50',
  },
  {
    id: 'tpl-promo',
    name: 'Promotional',
    description: 'Eye-catching promo email with image banner, headline and CTA button.',
    category: 'promo',
    blocks: STARTER_PROMO,
    thumbnailBg: 'bg-violet-50',
  },
  {
    id: 'tpl-onboarding',
    name: 'Onboarding',
    description: 'Welcome new users with a friendly onboarding email and get-started CTA.',
    category: 'onboarding',
    blocks: STARTER_ONBOARDING,
    thumbnailBg: 'bg-teal-50',
  },
  {
    id: 'tpl-reactivation',
    name: 'Reactivation',
    description: 'Re-engage lapsed users with a personalized we-miss-you message.',
    category: 'reactivation',
    blocks: STARTER_REACTIVATION,
    thumbnailBg: 'bg-amber-50',
  },
  {
    id: 'tpl-transactional',
    name: 'Transactional',
    description: 'Clean transactional email template for order confirmations and receipts.',
    category: 'transactional',
    blocks: STARTER_TRANSACTIONAL,
    thumbnailBg: 'bg-gray-50',
  },
]
