"use client";

import * as React from "react";
import { RiSparklingLine, RiRefreshLine, RiStopCircleLine, RiCheckLine, RiCloseLine } from "@remixicon/react";

export type AiTone = "warm_followup" | "cold_intro" | "reschedule_ask" | "closing_thanks";

const TONE_LABELS: Record<AiTone, string> = {
  warm_followup: "Warm follow-up",
  cold_intro: "Cold intro",
  reschedule_ask: "Reschedule ask",
  closing_thanks: "Closing thanks",
};

export type AiState = "idle" | "generating" | "done";

interface AiGenerateProps {
  state: AiState;
  tone: AiTone;
  progress?: number; // 0–100 when generating
  contextChips?: string[];
  /** When true and state=idle, collapse the full card into a small pill button */
  collapsed?: boolean;
  onToneChange: (tone: AiTone) => void;
  onGenerate: () => void;
  onRegenerate: () => void;
  onStop: () => void;
  onAccept: () => void;
  onDiscard: () => void;
  onTryAnotherTone: () => void;
  generatedLabel?: string; // e.g. "Generated by AI · 2.4s · Warm follow-up"
}

export function AiGenerate({
  state,
  tone,
  progress = 0,
  contextChips = [],
  collapsed = false,
  onToneChange,
  onGenerate,
  onRegenerate,
  onStop,
  onAccept,
  onDiscard,
  onTryAnotherTone,
  generatedLabel,
}: AiGenerateProps) {
  // ── Collapsed pill (idle + user has already typed content) ─────────────────
  if (state === "idle" && collapsed) {
    return (
      <div className="flex items-center gap-2 mb-2">
        <button
          onClick={onGenerate}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full border border-primary/40 bg-primary/5 text-primary text-xs font-semibold hover:bg-primary/10 transition-colors"
        >
          <RiSparklingLine size={13} />
          Regenerate with AI
        </button>
        <span className="text-[11px] text-foreground-muted">
          · {TONE_LABELS[tone]}
        </span>
        {/* Tone quick-switch pills */}
        <div className="flex items-center gap-1 ml-1">
          {(Object.keys(TONE_LABELS) as AiTone[]).map((t) => (
            <button
              key={t}
              onClick={() => onToneChange(t)}
              title={TONE_LABELS[t]}
              className={`px-2 py-0.5 rounded-full text-[11px] font-medium border transition-colors ${
                tone === t
                  ? "border-primary bg-primary/10 text-primary"
                  : "border-border text-foreground-muted hover:bg-background-subtle hover:text-foreground"
              }`}
            >
              {TONE_LABELS[t].split(" ")[0]}
            </button>
          ))}
        </div>
      </div>
    );
  }

  // ── Full idle card ──────────────────────────────────────────────────────────
  if (state === "idle") {
    return (
      <div className="rounded-xl border border-dashed border-primary/40 bg-primary/5 p-5 text-center">
        <div className="flex items-center justify-center mb-3">
          <div className="size-10 rounded-full bg-primary flex items-center justify-center">
            <RiSparklingLine size={18} className="text-white" />
          </div>
        </div>
        <p className="text-sm font-semibold mb-1">Generate this email automatically</p>
        <p className="text-xs text-foreground-muted mb-4">
          Drafted from your contact&apos;s segment, country, latest Discovery Call stage, and your last 3 emails together.
        </p>
        {/* Tone selector */}
        <div className="flex flex-wrap justify-center gap-2 mb-4">
          <span className="text-xs text-foreground-muted self-center">Tone:</span>
          {(Object.keys(TONE_LABELS) as AiTone[]).map((t) => (
            <button
              key={t}
              onClick={() => onToneChange(t)}
              className={`px-3 py-1.5 rounded-full text-xs font-medium border transition-colors ${
                tone === t
                  ? "border-primary bg-primary/10 text-primary"
                  : "border-border text-foreground hover:bg-background-subtle"
              }`}
            >
              {TONE_LABELS[t]}
            </button>
          ))}
        </div>
        <button
          onClick={onGenerate}
          className="inline-flex items-center gap-2 px-5 py-2.5 rounded-full bg-primary text-white text-sm font-semibold hover:opacity-90 transition-opacity"
        >
          <RiSparklingLine size={15} />
          Generate
        </button>
        <p className="text-xs text-foreground-muted mt-3">or write your own message below ↓</p>
      </div>
    );
  }

  if (state === "generating") {
    return (
      <div className="rounded-xl border border-primary/30 bg-primary/5 p-4">
        <div className="flex items-center gap-2 mb-3">
          <RiSparklingLine size={16} className="text-primary" />
          <span className="text-sm font-semibold">Drafting based on context...</span>
          <span className="ml-auto text-xs font-semibold text-primary">{progress}%</span>
        </div>
        {/* Progress bar */}
        <div className="h-1.5 rounded-full bg-border mb-3 overflow-hidden">
          <div
            className="h-full bg-primary rounded-full transition-all duration-300"
            style={{ width: `${progress}%` }}
          />
        </div>
        {/* Context chips */}
        {contextChips.length > 0 && (
          <div className="flex flex-wrap gap-2 mb-3">
            {contextChips.map((chip) => (
              <span key={chip} className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full border border-border bg-background text-xs font-medium text-foreground-muted">
                <RiCheckLine size={11} className="text-primary" />
                {chip}
              </span>
            ))}
          </div>
        )}
        {/* Skeleton lines */}
        <div className="space-y-2 mb-4">
          <div className="h-2.5 rounded bg-border/70 w-full" />
          <div className="h-2.5 rounded bg-border/70 w-4/5" />
          <div className="h-2.5 rounded bg-border/70 w-11/12" />
          <div className="h-2.5 rounded bg-border/70 w-3/4" />
          <div className="h-2.5 rounded bg-border/70 w-2/3" />
        </div>
        <div className="flex items-center justify-between">
          <button
            onClick={onStop}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full border border-red-300 bg-red-50 text-red-600 text-xs font-semibold hover:bg-red-100 transition-colors"
          >
            <RiStopCircleLine size={13} />
            Stop generating
          </button>
          <span className="text-[11px] text-foreground-muted">Powered by Twibbonize AI · v0.4</span>
        </div>
      </div>
    );
  }

  // state === "done"
  return (
    <div className="rounded-xl border border-primary/40 bg-primary/5 p-3">
      <div className="flex items-start gap-2">
        <div className="mt-0.5 size-6 rounded-full bg-primary/10 flex items-center justify-center shrink-0">
          <RiSparklingLine size={13} className="text-primary" />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-xs font-semibold text-primary truncate">
            {generatedLabel ?? `Generated by AI · ${TONE_LABELS[tone]}`}
          </p>
          <p className="text-[11px] text-foreground-muted">
            Review before sending. You can edit, regenerate, or accept as-is.
          </p>
        </div>
      </div>
      {/* Action bar */}
      <div className="flex flex-wrap items-center gap-2 mt-3 pt-3 border-t border-primary/20">
        <button
          onClick={onAccept}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-primary text-white text-xs font-semibold hover:opacity-90 transition-opacity"
        >
          <RiCheckLine size={12} />
          Accept &amp; edit
        </button>
        <button
          onClick={onRegenerate}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full border border-border bg-background text-xs font-semibold hover:bg-background-subtle transition-colors"
        >
          <RiRefreshLine size={12} />
          Regenerate
        </button>
        <button
          onClick={onTryAnotherTone}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full border border-border bg-background text-xs font-semibold hover:bg-background-subtle transition-colors"
        >
          Try another tone
        </button>
        <button
          onClick={onDiscard}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-red-500 hover:text-red-600 transition-colors ml-auto"
        >
          <RiCloseLine size={12} />
          Discard
        </button>
      </div>
    </div>
  );
}
